### ISSUE TITLE
提个bug，顺便问问灰度管理功能那里有没具体点的操作流程例子和文章，我想试试看怎么用，谢谢

### ISSUE THREAD

**Issue by freelyl** [saleson/fm-cloud#2]
policyGroupId应该是   policyId吧，这个导致swagger2里面的接口读不出 policy
public GrayPolicy getGrayPolicy(String policyId){
        for (GrayPolicy grayPolicy : list) {
            if(grayPolicy.getPolicyId().equals(policyGroupId)){
                return grayPolicy;
            }
        }
        return null;
    }

**Comment by saleson** [comment]
已修复。
例子在csdn搏客上有哈。
http://blog.csdn.net/mr_rain/article/details/79137522

**Comment by freelyl** [comment]
博客上的文章，我看过了，只说了原理上的东西，具体怎么调用swagger来实现整个流程还是没有说细。想知道一下操作流程和最终输出效果的例子

**Comment by saleson** [comment]
不好意思呢，  那个资料没有时间去写。  
swagger中的接口是用来做灰度的管理界面的了。 
前端很久没有去写了， 所以界面目前也没有做。
